version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://your-api-url-here
    restart: always
